import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useState } from 'react';
import BooksList from '../components/BooksList';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          <BooksList/>
        </div>
        <Link href='/add' className='underline text-blue-400 m-5 text-2xl'>Add</Link>
    </div>
  );
}
